# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63hat_service.proto\x12\x04grpc\"\x1c\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\"h\n\x07Message\x12\x10\n\x08senderID\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x63onversationID\x18\x03 \x01(\t\x12\"\n\ttimestamp\x18\x04 \x01(\x0b\x32\x0f.grpc.TimeStamp\"\x07\n\x05\x45mpty\"N\n\x0c\x43hatRoomInfo\x12\x13\n\x0bisConnected\x18\x01 \x01(\x08\x12\x16\n\x0e\x63onversationID\x18\x02 \x01(\t\x12\x11\n\tuserLimit\x18\x03 \x01(\x05\"4\n\x08\x43hatUser\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0e\x63onversationID\x18\x02 \x01(\t2\xf8\x01\n\x0b\x43hatService\x12-\n\x07\x43onnect\x12\x0e.grpc.ChatUser\x1a\x12.grpc.ChatRoomInfo\x12\x30\n\nDisconnect\x12\x0e.grpc.ChatUser\x1a\x12.grpc.ChatRoomInfo\x12)\n\x0bSendMessage\x12\r.grpc.Message\x1a\x0b.grpc.Empty\x12\x34\n\x11SubscribeMessages\x12\x0e.grpc.ChatUser\x1a\r.grpc.Message0\x01\x12\'\n\x0b\x46lushServer\x12\x0b.grpc.Empty\x1a\x0b.grpc.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TIMESTAMP']._serialized_start=28
  _globals['_TIMESTAMP']._serialized_end=56
  _globals['_MESSAGE']._serialized_start=58
  _globals['_MESSAGE']._serialized_end=162
  _globals['_EMPTY']._serialized_start=164
  _globals['_EMPTY']._serialized_end=171
  _globals['_CHATROOMINFO']._serialized_start=173
  _globals['_CHATROOMINFO']._serialized_end=251
  _globals['_CHATUSER']._serialized_start=253
  _globals['_CHATUSER']._serialized_end=305
  _globals['_CHATSERVICE']._serialized_start=308
  _globals['_CHATSERVICE']._serialized_end=556
# @@protoc_insertion_point(module_scope)
